" Load default Vim settings
source ~/.vim/config/all.vim

" Load colorscheme
silent! colorscheme ir_black

" Use antialiased fonts.
set antialias

" Use a minimal GUI.
set guioptions=Ace

" Don't beep when an error occurs.
set vb t_vb=
