#!/bin/sh
set -e

current=`pwd`


echo "Installing Vim settings..."

# Symlink RC files
files=("vimrc" "gvimrc")

for file in "${files[@]}"
do
  dest="$HOME/.$file"
  source="$current/rc/$file"

  echo "Creating symlink: .$file"
  ln -fs $source $dest
done


# Create Vim temp directory
tmp_directory="$current/tmp"
if [ ! -d "$tmp_directory" ]; then
  echo "Created Vim temp directory."
  mkdir $tmp_directory
fi


# Install Vundle
if [ ! -d "bundle/Vundle.vim" ]; then
  echo "Installing Vundle..."
  git clone git@github.com:gmarik/Vundle.vim.git bundle/Vundle.vim
fi

echo "Vim settings finished!"
